esphome:
  name: bttracker
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "YOUR SSID"
  password: "YOUR WIFI PASSWORD"
  
api:
web_server:
  port: 80
logger:
ota:

# Enable Bluetooth scanning for this ESP32
esp32_ble_tracker:

sensor:
  - platform: xiaomi_miflora
    mac_address: C4:7C:8D:63:CB:41
    temperature:
      name: "Monstera Deliciosa Temperature"
    moisture:
      name: "Monstera Deliciosa Soil Moisture"
    conductivity:
      name: "Monstera Deliciosa Fertilizer Level"
    illuminance:
      name: "Monstera Deliciosa Light Level"
